### ISSUE TITLE
Master React, Quick Code tutorial. Part 3

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-15#4]
https://medium.com/quick-code/lets-learn-react-chapter-3-components-components-components-3492f771d623

## Expected result

- [x] Read this tutorial chapter
- [x] follow code steps
- [x] move your code to this repository(at least one commit per day)
- [ ] explain to me, what did you learn from it in a few sentences(not less than 5)
- [ ] pass the test section
- [ ] after reviewing your progress and closing this issue - you can move to the next chapter.

## Test
- [ ] similar component for day checker is month checker. Create it.
- [ ] btw, can you have a some sort of component between month and day - week, right?
with ability(method) - to grab only work days, and other method for weekends?
- [ ] separate some of repeating functionality from that HTML code too...
- [ ] I want to have one array - that will contain days and month together. so when you'll need to render a 'calendar' table - you'll use 2 forEach methods.
- [ ] and i want to have all static data - like titles, image url, content - into one file, make it like array. sample: https://github.com/ChickenKyiv/recipe-search-react/tree/master/src/data
#1

**Comment by atherdon** [comment]
@Jobsy can you tell me - are you still working on this protject?

**Comment by Jobsy** [comment]
Morning sir,

With all due respect sir, I have completed project #4.

Or is there any correction, error, or bug you would want me to fix?

Regards,

**Comment by atherdon** [comment]
@Jobsy ok, while i'm checking it - you can move to the next chapters, ok?

**Comment by atherdon** [comment]
@Jobsy just opened a repo, and it looks strange. shall i clone it and update? i think this will help us to move forward with this course

**Comment by Jobsy** [comment]
Yes sir.

Cloning and updating would be a great idea.

While you doing that sir, I should be working on the next chapter.

Thanks sir.

Regards,

**Comment by atherdon** [comment]
working on your repo updates, please take a look in a few hours (master
branch)

**Comment by Jobsy** [comment]
I've checked the master branch.

Should I go ahead and clone it and start working on it sir?

**Comment by atherdon** [comment]
yeah, because previous version that you did - it was looks differently,
and i also cannot run it on ouyr local machine, so i create a clear
react-app from scratch, move your files into that folder(some files missing
btw, maybe you forgot to commit something) and push them to your repo

**Comment by Jobsy** [comment]
Noted sir.

Thanks for giving a helping hand!

On Mon, Jul 16, 2018 at 10:04 PM, Arthur Tkachenko <notifications@github.com

**Comment by Jobsy** [comment]
Good day sir,

Over the last ten days I've been trying hard to figure out how I can solve question 4 of the test.
 
My challenge is creating a forEach loop (to render a 'calendar' table ), that will loop over the days array and the months array, both contained in the same array. It could have been easy to loop if the array were treated independently.

Can you kindly give me a clue on how to go about this, because I'm stuck.

Besides, thank you sir for cleaning up and updating my code.

Regards,

**Comment by atherdon** [comment]
@Jobsy can you put a link to code line where you're experienced that issues?

**Comment by atherdon** [comment]
in order to create 2 foreaches that will help you to grab data from 2x array(month in our case) - you should understand in your head the structure of month array in your head.
for example - you know that one row of this array is related to week, one cell in that row related to weekday and also it's a day.

so i assume you were stuck because you trying to code the whole logic by putting all lines of code(as other interns will do). but i'll advice you to debug it deeply. this is why this assignemtn was created - in order to help you to learn arrays deeply.

So, how i'll do this assignment:
1) i need to have a 2x structure array.
2) i'll create a first forEach and inside it i'll `console.log` the index, and value and will see if each of elements that i have - displayed properly? if yeah, i'll go deeply.
3) i'll create a second forEach and will check how the second layer elements is returned by `console.log`

**Comment by Jobsy** [comment]
Ok sir

**Comment by Jobsy** [comment]
Good day sir,

I've just updated my src codes.

I was able to get the app to display both day and month simultaneously
(thanks to tips you gave me) but with errors (Warning: Each child in an
array or iterator should have a unique "key" prop).

Although I tried fixing the errors by using an "else if" statement instead
of just using an "else" statement to escape my "if" statement; yet the
errors persisted when view from the console.

Kindly assist.

Regards,

**Comment by atherdon** [comment]
in order to make this task completed you should explain what you've learned during reading this chapter. please do it

**Comment by atherdon** [comment]
when i run your code i see this issue:
![image](https://user-images.githubusercontent.com/1469198/43546397-2fc0cff2-95e1-11e8-9eda-37939c340d17.png)
please fix, so i'll be able to take a look on your results

**Comment by Jobsy** [comment]
Good day sir,

I've just updated my files.

I've also included the package.json file to fix the error you are getting
sir.

Regards.
